import { IEchoStyle } from "@/type";

const RIGHT_ECHO_STYLES: IEchoStyle[] = [
  {
    key: "right-echo-1",
    className: "absolute  ",
    style: {
      color: "#F5F5F5",
      right: "-10px",
      top: "2px",
      WebkitTextStrokeWidth: "0.88px",
      WebkitTextStrokeColor: "rgba(253, 123, 8, 0.7)",
      fontSize: "176.188px",
      fontStyle: "normal",
      fontWeight: 500,
      lineHeight: "88%",
      textTransform: "uppercase",
      textAlign: "center" as const,
      transform: "translate(35px, 0)",
      zIndex: 5,
      background: "#F5F5F5",
      boxShadow: "0 0 15px 5px #F5F5F5",
      borderRadius: "4px",
      fontFamily: '"Ciutadella TRIAL", sans-serif',
    },
  },
  {
    key: "right-echo-2",
    className: "absolute ",
    style: {
      color: "#F5F5F5",
      right: "-20px",
      top: "2px",
      WebkitTextStrokeWidth: "0.81px",
      WebkitTextStrokeColor: "rgba(253, 123, 8, 0.7)",
      fontFamily: '"Ciutadella TRIAL", sans-serif',
      fontSize: "161.525px",
      fontStyle: "normal",
      fontWeight: 500,
      lineHeight: "88%",
      textTransform: "uppercase",
      textAlign: "center" as const,
      transform: "translate(65px, 0)",
      zIndex: 4,
      background: "#F5F5F5",
      boxShadow: "0 0 15px 5px #F5F5F5",
      borderRadius: "4px",
    },
  },
  {
    key: "right-echo-3",
    className: "absolute -top-0 ",
    style: {
      color: "#F5F5F5",
      right: "-24px",
      WebkitTextStrokeWidth: "0.68px",
      WebkitTextStrokeColor: "rgba(253, 123, 8, 0.7)",
      fontFamily: '"Ciutadella TRIAL", sans-serif',
      fontSize: "135.973px",
      fontStyle: "normal",
      fontWeight: 500,
      lineHeight: "88%",
      textTransform: "uppercase",
      textAlign: "center" as const,
      transform: "translate(95px, 15px)",
      zIndex: 3,
      top: "2px",
      background: "#F5F5F5",
      boxShadow: "0 0 15px 5px #F5F5F5",
      borderRadius: "4px",
    },
  },
];
const LEFT_ECHO_STYLES: IEchoStyle[] = [
  {
    key: "left-echo-1",
    className: "absolute -top-0 -left-4 z-30",
    style: {
      color: "#F5F5F5",
      WebkitTextStrokeWidth: "0.88px",
      WebkitTextStrokeColor: "rgba(253, 123, 8, 0.7)",
      fontFamily: '"Ciutadella TRIAL", sans-serif',
      fontSize: "176.188px",
      fontStyle: "normal",
      fontWeight: 500,
      lineHeight: "88%",
      textTransform: "uppercase",
      textAlign: "center" as const,
      transform: "translate(-35px, 0) rotate(-10deg)",
      zIndex: 5,
      background: "#F5F5F5",
      boxShadow: "0 0 15px 5px #F5F5F5",
      borderRadius: "4px",
    },
  },
  {
    key: "left-echo-2",
    className: "absolute top-0 -left-7 z-20",
    style: {
      color: "#F5F5F5",
      WebkitTextStrokeWidth: "0.81px",
      WebkitTextStrokeColor: "rgba(253, 123, 8, 0.7)",
      fontFamily: '"Ciutadella TRIAL", sans-serif',
      fontSize: "161.525px",
      fontStyle: "normal",
      fontWeight: 500,
      lineHeight: "88%",
      textTransform: "uppercase",
      textAlign: "center" as const,
      transform: "translate(-65px, 0) rotate(-10deg)",
      zIndex: 4,
      background: "#F5F5F5",
      boxShadow: "0 0 15px 5px #F5F5F5",
      borderRadius: "4px",
    },
  },
  {
    key: "left-echo-3",
    className: "absolute top-0 -left-9 z-10",
    style: {
      color: "#F5F5F5",
      WebkitTextStrokeWidth: "0.68px",
      WebkitTextStrokeColor: "rgba(253, 123, 8, 0.7)",
      fontFamily: '"Ciutadella TRIAL", sans-serif',
      fontSize: "135.973px",
      fontStyle: "normal",
      fontWeight: 500,
      lineHeight: "88%",
      textTransform: "uppercase",
      textAlign: "center" as const,
      transform: "translate(-95px, 15px) rotate(-10deg)",
      zIndex: 3,
      background: "#F5F5F5",
      boxShadow: "0 0 15px 5px #F5F5F5",
      borderRadius: "4px",
    },
  },
];

export { LEFT_ECHO_STYLES, RIGHT_ECHO_STYLES };
