import { Miner } from "@/type";

export const LEADERBOARD_DATA: Miner[] = [
  {
    rank: 1,
    hotkey: "5OfgJFKj5BUccQjNrP...",
    minerId: 190,
    averageAccuracy: 62.1,
    numberOfEvents: 105,
    averagePeerScore: 1.23,
  },
  {
    rank: 2,
    hotkey: "5OfgJFKj5BUccQjNrP...",
    minerId: 171,
    averageAccuracy: 59.05,
    numberOfEvents: 98,
    averagePeerScore: 1.21,
  },
  {
    rank: 3,
    hotkey: "5OfgJFKj5BUccQjNrP...",
    minerId: 153,
    averageAccuracy: 62.8,
    numberOfEvents: 12,
    averagePeerScore: 1.2,
  },
  {
    rank: 4,
    hotkey: "5OfgJFKj5BUccQjNrP...",
    minerId: 231,
    averageAccuracy: 61.8,
    numberOfEvents: 89,
    averagePeerScore: 1.19,
  },
  {
    rank: 5,
    hotkey: "5OfgJFKj5BUccQjNrP...",
    minerId: 126,
    averageAccuracy: 63.1,
    numberOfEvents: 104,
    averagePeerScore: 1.18,
  },
  {
    rank: 6,
    hotkey: "5OfgJFKj5BUccQjNrP...",
    minerId: 167,
    averageAccuracy: 64.0,
    numberOfEvents: 80,
    averagePeerScore: 1.17,
  },
  {
    rank: 7,
    hotkey: "5OfgJFKj5BUccQjNrP...",
    minerId: 168,
    averageAccuracy: 62.1,
    numberOfEvents: 72,
    averagePeerScore: 1.17,
  },
  {
    rank: 8,
    hotkey: "5OfgJFKj5BUccQjNrP...",
    minerId: 102,
    averageAccuracy: 62.1,
    numberOfEvents: 64,
    averagePeerScore: 1.64,
  },
  {
    rank: 9,
    hotkey: "5OfgJFKj5BUccQjNrP...",
    minerId: 190,
    averageAccuracy: 62.1,
    numberOfEvents: 56,
    averagePeerScore: 1.4,
  },
  {
    rank: 10,
    hotkey: "5OfgJFKj5BUccQjNrP...",
    minerId: 190,
    averageAccuracy: 62.1,
    numberOfEvents: 56,
    averagePeerScore: 1.4,
  },
];
