import type { Metadata } from "next";
import { Cormorant_Upright } from "next/font/google";
import "./globals.css";

// Google font
const cormorant = Cormorant_Upright({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-cormorant",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.cdnfonts.com/css/ciutadella-trial"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${cormorant.variable} font-ciutadella antialiased`}
        style={{
          fontFamily: "'Ciutadella TRIAL', sans-serif",
          background: "#F5F5F5",
        }}
      >
        <section className="w-[1440px] mx-auto py-10">{children}</section>
      </body>
    </html>
  );
}
